// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvvdzdpzukqjjmmbmobh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2dmR6ZHB6dWtxamptbWJtb2JoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2Mjc1NTMsImV4cCI6MjA3OTIwMzU1M30.qIn_kOKCHLo9pCgIfvMFo96GgyQgYqLDGk7sd_6g_dE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});